return {
  -- {
  --   'nvim-lualine/lualine.nvim',
  --   event = 'VeryLazy',
  --   -- See `:help lualine.txt`
  --   opts = {
  --     options = {
  --       icons_enabled = true,
  --       globalstatus = true,
  --       component_separators = { left = '', right = '' },
  --       section_separators = { left = '', right = '' },
  --       theme = 'auto',
  --       disabled_filetypes = {
  --         statusline = {},
  --         winbar = {},
  --       },
  --       ignore_focus = {},
  --       always_divide_middle = true,
  --       refresh = {
  --         statusline = 1000,
  --         tabline = 1000,
  --         winbar = 1000,
  --       },
  --     },
  --     sections = {
  --       lualine_a = {
  --         {
  --           'mode',
  --           -- Show one word: N, I or V
  --           fmt = function()
  --             local mode = vim.fn.mode()
  --             if mode == 'n' then
  --               return 'N'
  --             elseif mode == 'i' then
  --               return 'I'
  --             elseif mode == 'v' then
  --               return 'V'
  --             end
  --           end,
  --         },
  --       },
  --       lualine_b = { 'branch', 'diff', 'diagnostics' },
  --       lualine_c = { 'filename' },
  --       lualine_x = { 'encoding', 'fileformat', 'filetype' },
  --       lualine_y = {},
  --       lualine_z = { 'location' },
  --     },
  --     inactive_sections = {
  --       lualine_a = {},
  --       lualine_b = {},
  --       lualine_c = { 'filename' },
  --       lualine_x = { 'location' },
  --       lualine_y = {},
  --       lualine_z = {},
  --     },
  --     tabline = {},
  --     winbar = {},
  --     inactive_winbar = {},
  --     extensions = {},
  --   },
  -- },
}
